partial davinci build fix/cleanup -- mmc
Build fixes and cleanup for DaVinci MMC.  Cleanups are partial, and
include: whitespace (including "only tabs for indents"), line length
fixes, removing inappropriate brackets and blank lines, and more.

Also convert to being a platform_driver.

It's down to needing a substantive change before it compiles again:

  CC [M]  drivers/mmc/host/davinci_mmc.o
drivers/mmc/host/davinci_mmc.c: In function 'mmc_davinci_start_dma_transfer':
drivers/mmc/host/davinci_mmc.c:428: error: 'struct mmc_request' has no member named 'buffer'
drivers/mmc/host/davinci_mmc.c:458: error: 'struct mmc_request' has no member named 'buffer'
drivers/mmc/host/davinci_mmc.c: In function 'mmc_davinci_prepare_data':
drivers/mmc/host/davinci_mmc.c:614: error: 'struct mmc_request' has no member named 'buffer'
make[3]: *** [drivers/mmc/host/davinci_mmc.o] Error 1
make[2]: *** [drivers/mmc/host] Error 2
make[1]: *** [drivers/mmc] Error 2
make: *** [drivers] Error 2

That translates as "needs to use *only* scatterlist operations".

After it works again, there's still a lot that will need fixing
before an upstream merge, including moving device creation over
with board/chip init logic..

Signed-off-by: David Brownell <dbrownell@users.sourceforge.net>
Signed-off-by: Kevin Hilman <khilman@mvista.com>